[sgx]
isvprodid = 123
isvsvn = 321
nonpie_binary = true
enclave_size = "2G"
max_threads = 256
thread_num = 256
allowed_files = [ "file:/tmp", "file:/etc/apt/apt.conf.d", "file:/etc/apt/apt.conf", "file:/etc/default/apport", "file:/etc/nsswitch.conf", "file:/etc/group", "file:/etc/passwd", "file:/etc/host.conf", "file:/etc/hosts", "file:/etc/gai.conf", "file:/etc/resolv.conf", "file:/etc/fstab",]
remote_attestation = "none"
debug = false
require_avx = false
require_avx512 = false
require_mpx = false
require_pkru = false
require_amx = false
support_exinfo = false
enable_stats = false
[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/libsysdb.so"

[[sgx.trusted_files]]
uri = "file:/usr/bin/python3"

[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/"

[[sgx.trusted_files]]
uri = "file:/lib/x86_64-linux-gnu/"

[[sgx.trusted_files]]
uri = "file:/usr//lib/x86_64-linux-gnu/"

[[sgx.trusted_files]]
uri = "file:/usr/lib/python3.8/"

[[sgx.trusted_files]]
uri = "file:/usr/lib/python3/dist-packages/"

[[sgx.trusted_files]]
uri = "file:demo.py"

[loader]
entrypoint = "file:/usr/lib/x86_64-linux-gnu/gramine/libsysdb.so"
log_level = "error"
insecure__use_cmdline_argv = true

[libos]
entrypoint = "/usr/bin/python3"

[fs]
[[fs.mounts]]
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc"
path = "/lib"

[[fs.mounts]]
uri = "file:/lib/x86_64-linux-gnu"
path = "/lib/x86_64-linux-gnu"

[[fs.mounts]]
uri = "file:/usr"
path = "/usr"

[[fs.mounts]]
uri = "file:/etc"
path = "/etc"

[[fs.mounts]]
uri = "file:/tmp"
path = "/tmp"

[loader.env]
LD_LIBRARY_PATH = "/lib:/usr/lib:/lib/x86_64-linux-gnu:/usr//lib/x86_64-linux-gnu"
